In [1]:
import numpy as np

In [2]:
x = np.array([1.0, 2.0, 3.0])

print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

In [3]:
y = np.array([2.0, 4.0, 6.0])

print(x + y)
print(x - y)
print(x * y)
print(x / y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [4]:
x / 2.0

array([0.5, 1. , 1.5])

In [5]:
A = np.array([[1, 2], [3, 4]])

print(A)
A.shape, A.dtype

[[1 2]
 [3 4]]


((2, 2), dtype('int64'))

In [6]:
B = np.array([[5, 6], [7, 8]])

print(A * B)
print(A - B)

B * 10

[[ 5 12]
 [21 32]]
[[-4 -4]
 [-4 -4]]


array([[50, 60],
       [70, 80]])

In [7]:
C = np.array([11, 22])

print(A + C)
print(A * C)

[[12 24]
 [14 26]]
[[11 44]
 [33 88]]


In [8]:
X = np.array([A, B])

print(X)
print(X[0])
print(X[0][0])
print(X[0][0][0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 2]
 [3 4]]
[1 2]
1


In [9]:
X = X.flatten()

print(X)
print(X[np.array([0, 2, 4, 6])])

print(X > 5)
print(X[X > 5])

[1 2 3 4 5 6 7 8]
[1 3 5 7]
[False False False False False  True  True  True]
[6 7 8]
